language: python

services:
  - docker

python:
  - "3.7"
cache: pip

before_install:
  - docker build -t winorbit/test-bot:newtag .

install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests

after_success:
  - docker login -u winorbit -p X2GD6FKDTGmKG4V
  - docker build -t winorbit/test-bot:newtag .
  - docker push winorbit/test-bot:newtag

