version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install -r requirements.txt
            python -m unittest tests
          name: Test
      - run:
          command: |
            docker login -u winorbit -p X2GD6FKDTGmKG4V
            docker build -t winorbit/test-bot:newtag .
            docker push winorbit/test-bot:newtag

workflows:
  main:
    jobs:
      - build-and-test
